"""empty message

Revision ID: 0d25979a0c81
Revises: 0721c85bbebf
Create Date: 2023-10-22 11:24:40.960716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d25979a0c81'
down_revision = '0721c85bbebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_search_pattern', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('item_title_template', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('item_link_template', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('item_content_template', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_column('item_content_template')
        batch_op.drop_column('item_link_template')
        batch_op.drop_column('item_title_template')
        batch_op.drop_column('address')
        batch_op.drop_column('item_search_pattern')

    # ### end Alembic commands ###
